version: "3.3"
services:
  inter-op-layer-receiver:
    image: openjdk:11
    container_name: "inter-op-layer-receiver"
    ports:
      - 8080:8080
    volumes:
      - "../package1/inter-op-layer-receiver/target/inter-op-layer-receiver-0.0.1.jar:/usr/java_app/app.jar"
    command: bash -c "java -jar app.jar"
    working_dir: /usr/java_app
    networks:
      - dockernetwork
networks:
  dockernetwork:
    name: dockernetwork
    driver: bridge    