spring:
  application:
    name: connector-opencrvs
  jackson:
    default-property-inclusion: non-null

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: SearchRequestQueue
  exchange:
    name: SearchExc
  routing:
    key: search_req_key

server:
  port: 7170
crvs:
  endpoint: http://43.205.77.129:5001/fhir

