spring:
  application:
    name: connector-mosip
  jackson:
    default-property-inclusion: non-null
  cloud:
    config:
      enabled: false
server:
  port: 7200 
eureka:
  client: 
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
mosip:
  hostname: https://api-internal.mosip-accessh.net
  authentication-demo-service: http://localhost:8082
  RPMISPkey: qQUOlhjmKLs4Ne8Zo2vAcPCxmO5mQm58cbFxn2KcEjrwexP1Cp
  PARTNERID: 713
  APIkey: 529514
  token: eyJ4NWMiOlsiTUlJRGt6Q0NBbnVnQXdJQkFnSUlWQU1yU0V0SHpjQXdEUVlKS29aSWh2Y05BUUVMQlFBd2RqRUxNQWtHQTFVRUJoTUNTVTR4Q3pBSkJnTlZCQWdNQWt0Qk1SSXdFQVlEVlFRSERBbENRVTVIUVV4UFVrVXhEVEFMQmdOVkJBb01CRWxKVkVJeElEQWVCZ05WQkFzTUYwMVBVMGxRTFZSRlEwZ3RRMFZPVkVWU0lDaFFUVk1wTVJVd0V3WURWUVFEREF4M2QzY3ViVzl6YVhBdWFXOHdIaGNOTWpJeE1qRTVNRFF6T0RNMVdoY05Nak14TWpFNU1EUXpPRE0xV2pCWk1Rc3dDUVlEVlFRR0V3SkpUakVMTUFrR0ExVUVDQXdDUzBFeEREQUtCZ05WQkFvTUF6VXhOekVhTUJnR0ExVUVDd3dSU1VSQkxWUkZVMVF0VDFKSExWVk9TVlF4RXpBUkJnTlZCQU1NQ2xCQlVsUk9SVkl0Y25Bd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNFZmFON1F0R2EzQ0kxcnE0d2UyQ0ROSk5Qdm5pWWNxY3B5WGdjM2dkUE1jT2hMdC9lcUJFbzFVbEVkdDNIY1k0ZXFzL1k2Rlo1V09HdzRidUpwdENMd29iM0xzSFlUd0FxY0dCak4wQ3F3RUtKMlcvMnN6MFV6cElmVlRQU2ZaeWRLaTRFeTF6TFF5TXdCNWw3Vkh5K3hNRklaZmNKV2xkRVl6KzFEOFlXRmFZK1RMMmxMWHNoY2pyQXk0UkNhbi9Wc2RHU0doWWNpbSt1UUdxN1lWWExNTWhzN0s2M2FEU3dGYlhvMmppQVFwcWZKMUJVbDIxYU5WSTZNenBzVU1RMEpUcTFIY2ttRXlVbnlDWFd6RlhRWmYxMFZXTEZiLzZMRTVVdEt6TlF1dGwyTE9scEp5Q1ZxaUdvVkc2dHR5SDRaVnR4SmxsOGtYeU9LVTNibUQrckFnTUJBQUdqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNUEZYMXFSeFZjdTJvQy9YN2pLYlV2MUhucnZNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFYcFE0ZUpsNzB2bWhsZUpVSllSYWJxSmQ0a2t6bEFrZlJHendLb1dnTkJIR0xsYW1Dd0w5bFVESUNPV1lnS05DVWF1bVZaVlpINThNb05CSElEWnU3ZlI0RWlSTWVLK1poQ25DS21MT21sY0FWbVEzU0lHSS8ybTRxRUlmRm8zVGw1MFl0aUcvUGIxU2ZnVTlhOU9VZHNJRDNNdlRaUWJ2K2pKa0tLRlBtOHZsWXZocnBySVBmbjhtYW14RFN1bmxZdnFvUjc5ZVo2R0ZlSXcrZE45dVZKYnlkY0VFOGZnZ0VBR0dqVG1iSE9UWTZoUkhJNlpJbjA3ZlRXbEp6THBTdURiT1daT0pabXNLWlpJVjVZTWMrVm1BSUw2QmtINGZETzE1SEtzc3Y2VFhBUU5uUERZTXFqbERQNFljYlFZa2hzekRnenU3MWt3eHIzRnFpSFdMenc9PSJdLCJhbGciOiJSUzI1NiJ9..FO3Mk3BuE3yEvCzbyaoYf0m6bq998M0NAfaksTn9UlsA2RBQ8duF0c1qsUdolwQ_Vv-E9Xl0PGHzKgSGXC-AgZMksBrqB14v2dV3Y0DEGIOmTfoFESYmaNLI21Ixyt9oCHLlv3EcPkzCwISasg-2XWrwFlOsymHSk5r773qGpYBxGbRmit8dObH0HcF8knoSycabv_cjDuocOLVHN3e48R7E9PvHxmcn1PN7Pasgbfh_FExnhleVatnnCUiL3UZ9MqJ37ewwjR5pEHtwzeRavwzsfAOd1sdQ75V6rk5OaBb3lLJMs7PtAlW-4roza-uPFvNt5VwCPIUhCeIBpR5NXA
clientId: mosip-regproc-client
secretKey: R397g93s2CpLx778
appId: regproc
ida:
  reference:
    id: PARTNER
mispLicenseKey: qQUOlhjmKLs4Ne8Zo2vAcPCxmO5mQm58cbFxn2KcEjrwexP1Cp
partnerId: 713
partnerApiKey: 529514
