spring:
  application:
    name: dci_apis_springboot_server
  jackson:
    default-property-inclusion: non-null
server:
  port: 7115
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true



