spring:
  application:
    name: SBL-CRVS-SUBSCRIBER
  jackson:
    default-property-inclusion: non-null 
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
server:
  port: 9996 
eureka:
  client: 
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
