package org.spdci.enums;

public enum SearchStatusReasonCode {
    RJCT_ACTION_INVALID,
    RJCT_ACTION_NOT_SUPPORTED,
    RJCT_ENCRYPTION_ALGORITHM_INVALID,
    RJCT_ENCRYPTION_ALGORITHM_MISSING,
    RJCT_ERRORS_TOO_MANY_REQUESTS,
    RJCT_FILTER_INVALID,
    RJCT_MESSAGE_ID_DUPLICATE,
    RJCT_MESSAGE_TS_INVALID,
    RJCT_PAGINATION_INVALID,
    RJCT_REFERENCE_ID_DUPLICATE,
    RJCT_REFERENCE_ID_INVALID,
    RJCT_SIGNATURE_KEY_MISSING,
    RJCT_SORT_INVALID,
    RJCT_TIMESTAMP_INVALID,
    RJCT_TOTAL_COUNT_INVALID,
    RJCT_TOTAL_COUNT_LIMIT_EXCEEDED,
    RJCT_VERSION_INVALID,
    RJCT_SEARCH_CRITERIA_INVALID,
    RJCT_SEARCH_TOO_MANY_RECORDS_FOUND
}
